microsub:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  thruster0_position_controller:
    type: position_controllers/JointPositionController
    joint: microsub/thruster_0_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  thruster1_position_controller:
    type: position_controllers/JointPositionController
    joint: microsub/thruster_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  thruster2_position_controller:
    type: position_controllers/JointPositionController
    joint: microsub/thruster_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  thruster3_position_controller:
    type: position_controllers/JointPositionController
    joint: microsub/thruster_3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
