<?xml version="1.0"?>
<robot  xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find uuv_descriptions)/models/common/urdf/common.urdf.xacro"/>
  <xacro:include filename="$(find uuv_sensor_ros_plugins)/urdf/sensor_snippets.xacro"/>
  <xacro:include filename="$(find microsub_description)/urdf/snippets.xacro"/>
  <xacro:include filename="$(find uuv_gazebo_ros_plugins)/urdf/snippets.xacro"/>

  <!-- Parameters -->
  <xacro:property name="mass" value="10"/>
  <xacro:property name="volume" value="0.011054"/>
  <!-- <xacro:property name="cog" value="0 0 0.02535"/> -->
  <xacro:property name="cog" value="0 0 0"/>
  <xacro:property name="cob" value="0 0 0.155"/>
  <xacro:property name="rho" value="1028"/>

  <xacro:property name="x_size" value="0.448"/>
  <xacro:property name="y_size" value="0.2384"/>
  <xacro:property name="z_size" value="0.28066"/>

  <xacro:property name="equivalent_radius" value="${0.5*z_size}"/>

  <xacro:property name="visual_mesh_file" value="file://$(find microsub_description)/meshes/vehicle.dae"/>
  <xacro:property name="collision_mesh_file" value="file://$(find microsub_description)/meshes/vehicle.stl"/>

  <xacro:macro name="microsub_base" params="namespace debug inertial_reference_frame">

      <link name="${namespace}/base_link">
        <inertial>
          <mass value="${mass}" />
          <origin xyz="${cog}" rpy="0 0 0"/>
          <inertia ixx="${0.2*mass*y_size*y_size + 0.2*mass*z_size*z_size}" ixy="0.0" ixz="0.0"
                   iyy="${0.2*mass*x_size*x_size + 0.2*mass*z_size*z_size}" iyz="0.0"
                   izz="${0.2*mass*x_size*x_size + 0.2*mass*y_size*y_size}" />
          </inertial>

        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="0.13335 0.17145 0.08255"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="0.13335 0.17145 0.08255"/>
          </geometry>
        </visual>

      </link>

    <gazebo reference="${namespace}/base_link">
      <selfCollide>false</selfCollide>
    </gazebo>

    <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/${namespace}</robotNamespace>
      </plugin>
    </gazebo>

    <gazebo>
      <plugin name="${namespace}_uuv_plugin" filename="libunderwater_object_ros_plugin.so">
        <fluid_density>${rho}</fluid_density>
        <flow_velocity_topic>hydrodynamics/current_velocity</flow_velocity_topic>
        <debug>${debug}</debug>
        <link name="${namespace}/base_link">
          <neutrally_buoyant>0</neutrally_buoyant>
          <volume>${volume}</volume>
          <box>
            <width>${y_size}</width>
            <length>${x_size}</length>
            <height>${z_size}</height>
          </box>
          <center_of_buoyancy>${cob}</center_of_buoyancy>
          <hydrodynamic_model>
            <type>fossen</type>
            <added_mass>
              1.7182 0 0 0 0 0
              0 0 0 0 0 0
              0 0 5.468 0 0 0
              0 0 0 0 0 0
              0 0 0 0 1.2481 0
              0 0 0 0 0 0.4006
            </added_mass>
            <linear_damping>
              -11.7391 -20 -31.8678 -25 -44.9085 -5
            </linear_damping>
            <quadratic_damping>
              0 0 0 0 0 0
            </quadratic_damping>
          </hydrodynamic_model>
        </link>
      </plugin>
    </gazebo>

    <!-- Include the thruster modules -->
    <xacro:include filename="$(find microsub_description)/urdf/actuators.xacro"/>

    <!-- Include the sensor modules -->
    <xacro:include filename="$(find microsub_description)/urdf/sensors.xacro"/>

  </xacro:macro>
</robot>
